version: 5.0.0-alpha-dirty
0;1;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,;0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,;;;0,1,1,1,1,;20;20;8;8:
	aOhUVtZJvZJvXSwPN9dW9:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 40 0 44 4000 84
	aOhUVtZJvZJvXSwPN9dW9ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 109 2 77 10900 188
	aOhUVtZJvZJvXSwPN9dW9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 89 2 64 8900 155
	aOhUVtZJvZJvXSwPN9dW9MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 209 2 139 20900 350
	aOhUVtZJvZJvXSwPN9dW9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 82 0 64 8200 146
	aOhUVtZJvZJvXSwPN9dW9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 259 4 180 25900 443
	aOhUVtZJvZJvXSwPN9dW9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 15 0 22 1500 37
	aOhdOsUVtZJvXSwPN9dW9:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 1402 10 801 140200 2213
	aOhdOsUVtZJvXSwPN9dW9ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 7220 50 3887 722000 11157
	aOhdOsUVtZJvXSwPN9dW9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 5758 41 2982 575800 8781
	aOhdOsUVtZJvXSwPN9dW9MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 6811 51 3669 681100 10531
	aOhdOsUVtZJvXSwPN9dW9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 9844 71 5425 984400 15340
	aOhdOsUVtZJvXSwPN9dW9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 6968 71 3846 696800 10885
	aOhdOsUVtZJvXSwPN9dW9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 358 1 220 35800 579
	aOhdOsUVtZJvXSwPN9dW9cO+MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 3550 35 2000 355000 5585
	aOhdOsUVtZJvZJvPN9dW9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 9 0 15 900 24
	aOhdOsUVtZJvZJvPN9dW9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 2 0 7 200 9
	aOhdOsUVtZJvZJvPN9dW9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 6 0 14 600 20
	aOhdOsUVtZJvZJvPN9dW9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 15 0 23 1500 38
	aOhdOsUVtZJvZJvPN9dW9cO+MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 3 0 14 300 17
	aOhdOsUVtZJvZJvXSwPN9ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 8 0 16 800 24
	aOhdOsUVtZJvZJvXSwPN9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 112 3 77 11200 192
	aOhdOsUVtZJvZJvXSwPN9MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 44 0 40 4400 84
	aOhdOsUVtZJvZJvXSwPN9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 86 0 68 8600 154
	aOhdOsUVtZJvZJvXSwPN9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 65 1 58 6500 124
	aOhdOsUVtZJvZJvXSwPN9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 50 0 46 5000 96
	aOhdOsUVtZJvZJvXSwPN9dW9:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 65766 476 33758 6576600 100000
	aOhdOsUVtZJvZJvXSwPN9dW9ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 19917 124 10084 1991700 30125
	aOhdOsUVtZJvZJvXSwPN9dW9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 66752 460 32788 6675200 100000
	aOhdOsUVtZJvZJvXSwPN9dW9MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 66721 494 32785 6672100 100000
	aOhdOsUVtZJvZJvXSwPN9dW9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 65085 563 34352 6508500 100000
	aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 63838 501 35661 6383800 100000
	aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 63281 580 36139 6328100 100000
	aOhdOsUVtZJvZJvXSwPN9dW9cO+MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 64283 615 35102 6428300 100000
	aOhdOsUVtZJvZJvXSwdW9:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 17 0 20 1700 37
	aOhdOsUVtZJvZJvXSwdW9ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 2688 21 1490 268800 4199
	aOhdOsUVtZJvZJvXSwdW9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 1395 12 760 139500 2167
	aOhdOsUVtZJvZJvXSwdW9MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 2841 24 1568 284100 4433
	aOhdOsUVtZJvZJvXSwdW9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 1051 6 634 105100 1691
	aOhdOsUVtZJvZJvXSwdW9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 565 0 361 56500 926
	aOhdOsUVtZJvZJvXSwdW9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 365 2 223 36500 590
	aOhdOsUVtZJvZJvXSwdW9cO+MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 2271 21 1303 227100 3595
	aOhdOsZJvZJvXSwPN9dW9:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 75 3 59 7500 137
	aOhdOsZJvZJvXSwPN9dW9ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 244 2 159 24400 405
	aOhdOsZJvZJvXSwPN9dW9ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 299 4 181 29900 484
	aOhdOsZJvZJvXSwPN9dW9MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 299 3 191 29900 493
	aOhdOsZJvZJvXSwPN9dW9cO+:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 15 1 18 1500 34
	aOhdOsZJvZJvXSwPN9dW9cO+ME/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 59 0 52 5900 111
	aOhdOsZJvZJvXSwPN9dW9cO+ME/MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 123 2 85 12300 210
	aOhdOsZJvZJvXSwPN9dW9cO+MN/:
		aOhdOsUVtZJvZJvXSwPN9dW9cO+ME/MN/: 4 0 7 400 11
