name: Compile AHK to EXE

on:
  push:
    paths:
      - '**.ahk'
      - .github/workflows/ahk-compile.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AutoHotkey (download portable version)
      run: |
        Invoke-WebRequest -Uri https://www.autohotkey.com/download/ahk.zip -OutFile ahk.zip
        Expand-Archive ahk.zip -DestinationPath AHK

    - name: Compile AHK script
      run: |
        $compiler = "AHK\Compiler\Ahk2Exe.exe"
        $input = "SimpleTUOLiveSim.ahk"
        $output = "newSimpleTUOLiveSim.exe"
        & $compiler /in $input /out $output
      shell: powershell

    - name: Compile AHK script
      run: |
        Get-ChildItem -Path . -Filter "*.exe" | Remove-Item -Force

        $compiler = "AHK\Compiler\Ahk2Exe.exe"
        $input = "SimpleTUOptimizeStarter.ahk"
        $output = "newSimpleTUOptimizeStarter.exe"

        if (-Not (Test-Path $compiler)) {
          Write-Error "Compiler not found at $compiler"
          exit 1
        }
        if (-Not (Test-Path $input)) {
          Write-Error "AHK script not found at $input"
          exit 1
        }

        Write-Host "Compiling $input to $output..."
        & $compiler /in $input /out $output

        if (Test-Path $output) {
          Write-Host "Compilation succeeded: $output"
        } else {
          Write-Host "Compilation failed, listing files in the current directory:"
          Get-ChildItem -Path . | ForEach-Object { Write-Host $_.FullName }
          Write-Error "Compilation failed, no output file created."
          exit 1
        }

      shell: powershell

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: compiled-exe
        path: newSimpleTUOptimizeStarter.exe

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: compiled-live-exe
        path: newSimpleTUOLiveSim.exe
