name: Build Every Commit

on:
    push:
        branches: [ master , test_github_actions]
    pull_request:
        branches: [ master ]

jobs:
    build-darwin:
        runs-on: macOS-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Dependencies
                run: |
                    brew update
                    brew install boost
                    

            -   name: Build
                run: |
                    sudo xcode-select -s /Library/Developer/CommandLineTools
                    mkdir buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    echo !!! $(nproc)
                    make -j$(nproc)
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_darwin_${{github.sha}}
                    path: build/hello_darwin

    build-linux:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y libboost-all-dev 
            -   name: Build
                run: |
                    mkdir buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    make -j$(nproc)
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_linux_${{github.sha}}
                    path: build/hello_linux

    build-windows-x64:
        runs-on: windows-2019
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    set BOOST_ROOT=%BOOST_ROOT_1_72_0%
                    md buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -DBOOST_ROOT=%BOOST_ROOT_1_72_0% ..
                    cmake --build . --config Release
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_windows_x64_${{github.sha}}
                    path: build/hello_windows_x64.exe

