name: Build Every Commit

on:
    push:
        branches: [ master , test_github_actions]
    pull_request:
        branches: [ master ]

jobs:
    build-darwin:
        runs-on: macOS-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    sudo xcode-select -s /Library/Developer/CommandLineTools
                    mkdir buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    echo !!! $(nproc)
                    make -j$(nproc)
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_darwin_${{github.sha}}
                    path: build/hello_darwin

    build-linux:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y libboost-all-dev 
            -   name: Build
                run: |
                    mkdir buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release ..
                    make -j$(nproc)
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_linux_${{github.sha}}
                    path: build/hello_linux

    build-windows-x86:
        runs-on: self-hosted
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat"
                    md buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_windows_x86_${{github.sha}}
                    path: build/hello_windows_x86.exe

    build-windows-x64:
        runs-on: self-hosted
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
                    md buildit
                    cd buildit
                    cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
                    nmake
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: hello_windows_x64_${{github.sha}}
                    path: build/hello_windows_x64.exe

