name: pre-release

on: [push]

jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04  # Use older Ubuntu version

    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      # Build it
      - run: "./build/windows/requirements.sh"
      - run: "./build/windows/build.sh"
      - run: ./update_xml.sh
      - run: source build/windows/package.sh

      - name: Upload tuo
        uses: actions/upload-artifact@v4
        with:
          name: tuo
          path: |
            *.exe
            *.zip
