name: test

on: [push, pull_request]

jobs:
 release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get --yes install g++ make cmake libboost-all-dev 
    - name: build
      run: make test
    - name: test
      run: ./tuo-test --log_level=message