name: travis

on: [push]

jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags
      - run: "./build/windows/requirements.sh"
      - run: "./build/windows/build.sh"
      - run: ./update_xml.sh
      - run: "./build/windows/test.sh"
      - run: source build/windows/package.sh

      - name: Upload info.log
        uses: actions/upload-artifact@v3
        with:
          name: info_log
          path: |
            *.exe
            *.zip
